name: Publish OpenAPI definitions to ReadMe
on:
  push:
    branches:
      - main
    paths:
      - '*-api/**.json'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Sync Public API definition
        uses: readmeio/rdme@38a6ae8e01b83ff4672f3f8f35b72a16e267be39
        with:
          rdme: openapi upload core-api/core-api.json --slug=core-api.json --key=${{ secrets.README_API_KEY }}
      
      - name: Sync Channel API definition
        uses: readmeio/rdme@38a6ae8e01b83ff4672f3f8f35b72a16e267be39
        with:
          rdme: openapi upload channel-api/channel-api.json --slug=channel-api.json --key=${{ secrets.README_API_KEY }}
